### PR TITLE
PortalGun protection

### PR DESCRIPTION
**Pull request by Torins**
Hey Legobear.

Protection against portal gun portals wasn't working so I went and changed it.
There were two problems:
1) if it was a default portal, getBlock was called with block x and z, while it should be called with chunk dimensions.
2) When shot from very close the update method is called only once, but it ends after checking if the entity is moving, skipping protection checks.

I've redid the whole update method, so it does permission checking only when the ball collides with something, that way in case number two the very first update call has a collision and ends up checking permissions.
A side effect is that portal balls can now fly through towns, as long as they land on an area where they are permitted to create a portal.

Hopefully this way requires less processing than the previous one, but not sure about that.

There's one slight bug though: due to checking permissions for all blocks around the collided one, portals may refuse to work one block away from a town chunk. I would have to know on which block the 2nd part of the portal will appear, to correct this.

### CODE REVIEW

**Comment by jgoett154** [comment]
Hello Torins! Thanks for fixing that, I will accept it and test it out really quick. The side effect would be actually kinda cool to have anyways.

Also, does Portal Gun have any way to see which direction the portal is facing? You might be able to use that in combination with whether its placed on the floor, ceiling, wall, etc to make it work right against a town. Also, might you know of a way to add Vault integration without killing MyTown? I started and apparently Bukkit Plugins are not injected into the classpath. Loading the Vault classes are the only issue I am having and I can't think of any other options right this minute.

**Comment by Torins** [comment]
The MovingObjectPosition has information which side of a block it hit. As long as it hits a side I can just check one block above for perms. But if it hits the top or bottom of a block I need to find which other block I need to check. I suppose this can be deduced from the vectors I've used, but haven't tried that yet.

As for integration with bukkit plugins. I personally would love to decouple MyTown from forge PEx and add support for bukkit PEx, so mcpc+ servers don't have to run both PExes at the same time.
I haven't yet checked anything, but a quick google suggests that it is possible - there is a forge version of Dynmap (http://www.minecraftforum.net/topic/1543523-dynmap-dynamic-web-based-maps-for-minecraft/) and a bukkit plugin DynmapCBBridge (http://minecraft.curseforge.com/mc-mods/dynmapcbbridge/) which "(...) allows DynmapForge to access various Bukkit-based permissions managers (PermissionsEx, bPermissions, GroupManager).".

Both are open source, so perhaps looking into their code can help.

**Comment by Torins** [comment]
After taking a peek into the mod's and plugin's code, it seems very doable. 
I don't know when or if I'll try to do it though.

**Comment by jgoett154** [comment]
Hmm, interesting find there. Well, I did start on some integration and I pushed it to here quickly last night before I got off. I commented on what fails to work. I will look at the code for those and see if I can manage anything quickly. The way I am doing it is through try/catch statements, there is probably a better way to do it. I also have in place a "fallback" permissions system that can be used if no permission system is in place, but I haven't added code to that just yet.

Ok, he is taking a different approach from what I started doing. He is using a Bukkit Plugin to register a PermissionsHandler with Dynmap. The PermissionsHandler just contains common functions that are mapped to the Bukkit plugin that is being used for permissions, that shouldn't be too hard to manage actually.

**Comment by Torins** [comment]
Given the sudden need to make MyTown bukkit PEx compatible (forge PEx and bukkit PEx can't run at the same time), I've tried mikeprimm's way of passing the permissionsHandler and it seems to have worked.

The code is plain awful though, so I won't commit it. I'll show it on request, but I'll take my time trying to make some proper code before making a commit.

One thing to note though. When I tried to pass things during postInit in MyTown, it was called before the bukkit plugin managed to register his handler - so I delayed it until the first attempt to check permissions.

**Comment by jgoett154** [comment]
I have a working version as well. I may commit it, but im not satisfied with it just yet, but it fully works. I created a separate Bukkit Plugin that just uses MyTown as a sort of API. The Bukkit plugin registers with Vault, then the Bukkit plugin sets the "PermissionHandler" for MyTown and MyTown uses it when needed. Problem is, not all nodes work 100% like they should. Some work as ee.lutsu.alpha.mc.mytown.commands.CmdMyTownAdmin instead of the much cleaner mytown.adm.cmd and I am not sure why. I have reason to believe its something to do with the way MyTown handles commands, but I have yet to figure out why. I will commit my changes shortly and also upload the Bukkit plugin.

There is an error with ICommandSender in my code currently and I need to fix it, but I will commit and upload still.

Correction, I think I have fixed that error by simply casting ICommandSender to EntityPlayer only if it is an instance of EntityPlayer

Here is the Bukkit Plugin https://github.com/legobear154/MyTownCBBridge

**Comment by Torins** [comment]
I think a better way would be to edit forge PEx, and based on that, make an api mod that will allow any forge mod to use permissions.

The api would, through the bukkit plugin be supplied with handlers to interface with bukkit based permission plugins and if none are found (by the time the first perm request comes), it will fall back to the forge PEx implementation (which will have to be moved to a different package, not to interfere with bukkit PEx).

MyTown then could simply use the new api instead of current forge PEx.

That's what I would like to acomplish.

Also. From what I see with my limited tests, all perms have been granted when I gave myself a mytown.\* node, no need for the full ee.lutsu.(...) node. Could you give me and example of what needed the full node?

**Comment by jgoett154** [comment]
Ah, I see what you mean. That would work as well. Well, technically, I have a portion of the work done already, it would just have to be adapted to use the new api. This is the file I created and am using as a sort of api all PermissionHandler extends it https://github.com/legobear154/MyTown/blob/master/src/ee/lutsu/alpha/mc/mytown/PermissionsBase.java We might be able to use that as the base of the api, possibly adding more things to it if needed. And the plugin I wrote should be easily adapted to work with the api. Would you like me to make a repo for forge PEx as well really quick?

Also should say, I am still having a few small issues with the Bukkit plugin. Fields and methods supposedly not existing.

**Comment by Torins** [comment]
Sure, if you wish. I'll fork it so ya can keep an eye on commits and will do things at my own pace. The thing I needed ASAP is done, that being a patchwork way of making MyTown use bukkit PEx.

Now I can attempt to actually plan the code ahead, but given my style, it'll fail anyway and end up a monstrosity :)

P.S. I'm from EU, so this is the moment when I go to sleep. Don't hurry with anything. I won't be able (if willing) to sit down to code sooner than evening my time anyway.

**Comment by jgoett154** [comment]
I will create a repo then. I am taking the approach of using Vault to interface with a large portion of different Bukkit perm plugins. One codebase to rule them all ;) And ok, I am from the US so its still day out. :) Ill attempt to fix my issues, then work on separating everything some to see what I can get in the end. I really need to figure out these supposed fields and methods that don't exist even though my minecraft.jar says they do :p I guess thats Bukkit for you.

**Comment by Torins** [comment]
Eh, if you're already that far, I guess I'll give up on doing the same code twice ;)

**Comment by jgoett154** [comment]
Haha, sorry, I started just before asking you if you knew of a way to :p All be it, when you pointed out Dynmap I completely dumped my original way :p

**Comment by jgoett154** [comment]
Figured I would tell you, Everything is working now with my current setup! Now onto separating it and making PEx an API :)

Here is the repo for PEx https://github.com/legobear154/PermissionsEX

**Comment by jgoett154** [comment]
Hey Torins, I have everything separated now, here is the mod that holds the API and PEX https://github.com/legobear154/ForgePerms and here is the Bukkit plugin https://github.com/legobear154/ForgePermsCBBridge. MyTown has integration with it, I haven't tested extensively but it works. I think I will create my own topic on minecraftforum with download links to everything including MyTown. If you find something wrong in the code, etc please feel free to say something. One thing I haven't figured out how to do is keep forge PEx from loading when its not needed.

**Comment by Torins** [comment]
I'm afraid I don't have an idea currently either (I will try researching the topic if you wish), but if you worry that forge PEx loading will prevent bukkit PEx from loading - refactor the code to a different package. As long as the classes are in a different package, I _think_ they should work.

**Comment by jgoett154** [comment]
I already re-factored it into a different package and it works with Bukkit PEx just fine, I was just wondering if there was a way to auto-disable it so it doesn't sit there doing nothing all the time.

**Comment by Torins** [comment]
Well, you could just split it into a yet another mod, so people have a choice of including it or not. MyTown depends on the API, so it will still work fine.

I'll give ya a call if I find a way to not load the classes, but I have a feeling it's not possible as long as they're inside a jar that's in the /mods folder.

**Comment by jgoett154** [comment]
Yea, I could do that. A quick google search has shown nothing yet. There is a method to set the enable status of a mod, but it doesn't seem to do anything when I use it.

**Comment by Torins** [comment]
Lego. Do you use Skype, or any kind of IM app?
What about irc? Catch me on ftb-craft's channel please.

**Pull request merged**
